# Copyright 2025 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Test PyTorch Ops
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test_torch_ops.yml"
      - "torch_ops/**"
  pull_request:
    paths:
      - ".github/workflows/test_torch_ops.yml"
      - "torch_ops/**"
  workflow_dispatch:
  schedule:
    # Runs at 3:00 PM UTC, which is 8:00 AM PST
    - cron: "0 15 * * *"

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-pytorch-ops:
    if: ${{ github.repository_owner == 'iree-org' || github.event_name != 'schedule' }}
    runs-on: ubuntu-24.04
    env:
      VENV_DIR: ${{ github.workspace }}/.venv
      CONFIG_FILE_PATH: torch_ops/configs/torch_ops_cpu_llvm_sync.json
      HTML_REPORT_PATH: torch_ops/torch_ops_test_report_cpu_llvm_sync.html
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Install Python packages.
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
      - name: Setup Python venv
        run: python3 -m venv ${VENV_DIR}
      - name: Install IREE nightly release Python packages
        run: |
          source ${VENV_DIR}/bin/activate
          python3 -m pip install -r torch_ops/requirements-iree.txt

      # Run tests and output new config files as needed.
      - name: Run Torch ops test suite
        continue-on-error: true
        run: |
          source ${VENV_DIR}/bin/activate
          pytest torch_ops/ \
            -n auto \
            -rA \
            --timeout=30 \
            --durations=10 \
            --html=${HTML_REPORT_PATH} \
            --self-contained-html \
            --report-log=/tmp/torch_ops_cpu_logs.json \
            --config-files=${CONFIG_FILE_PATH}
      - name: Upload HTML report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: torch_ops_test_report_cpu_llvm_sync.html
          path: ${{ env.HTML_REPORT_PATH }}
